version: '3.4'

services:
  foodorder.api:
    image: ${DOCKER_REGISTRY-}foodorderapi
    build:
      context: .
      dockerfile: Order/FoodOrder.Api/Dockerfile

  foodorder.delivery.api:
    image: ${DOCKER_REGISTRY-}foodorderdeliveryapi
    build:
      context: .
      dockerfile: DeliverySerive/FoodOrder.Delivery.Api/Dockerfile


  foodorder.payment.api:
    image: ${DOCKER_REGISTRY-}foodorderpaymentapi
    build:
      context: .
      dockerfile: PaymentService/FoodOrder.Payment.Api/Dockerfile
  
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "15671:15671"
    - "15672:15672"